export const IntentEnum = {
    WEB_PROJECT_ADD_TRAINSET: 'web.project.add.trainset',
    WEB_PROJECT_CHANGE_TRAINSET_PRESET: 'web.project.change.trainset.preset',
    WEB_PROJECT_SAVE_TRAINSET_PRESET: 'web.project.save.trainset.preset',
    WEB_TRAINSET_DELETE_CARRIAGE_TRAINSET: 'web.trainset.delete.carriage.trainset',
    WEB_TRAINSET_ADD_CARRIAGE_TRAINSET: 'web.trainset.add.carriage.trainset',
    WEB_TRAINSET_UPDATE_CARRIAGE_TRAINSET: 'web.trainset.update.carriage.trainset',
    WEB_CARRIAGE_TRAINSET_ADD_CARRIAGE_PANEL: 'web.carriage.trainset.add.carriage.panel',
    WEB_PANEL_GET_TEMPLATE_IMPORT_PANEL: 'web.panel.get.template.import.panel',
    WEB_PANEL_IMPORT_PANEL: 'web.panel.import.panel',
    WEB_RAW_MATERIAL_GET_TEMPLATE_IMPORT_RAW_MATERIAL: 'web.raw.material.get.template.import.raw.material',
    WEB_RAW_MATERIAL_IMPORT_RAW_MATERIAL: 'web.raw.material.import.raw.material',
    WEB_CARRIAGE_GET_TEMPLATE_IMPORT_CARRIAGE: 'web.carriage.get.template.import.carriage',
    WEB_CARRIAGE_IMPORT_CARRIAGE: 'web.carriage.import.carriage',
    WEB_STEP_GET_TEMPLATE_IMPORT_STEP: 'web.step.get.template.import.step',
    WEB_STEP_IMPORT_STEP: 'web.step.import.step',
};
