<?php

namespace App\Services;

use App\Models\CustomAttachmentMaterial;
use App\Models\PanelAttachment;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;
use App\Http\Resources\PanelAttachmentResource;
use App\Support\Enums\PanelAttachmentStatusEnum;
use App\Support\Enums\PanelAttachmentHandlerHandlesEnum;
use App\Support\Interfaces\Services\SerialPanelServiceInterface;
use App\Support\Interfaces\Services\PanelAttachmentServiceInterface;
use App\Support\Interfaces\Repositories\PanelAttachmentRepositoryInterface;
use App\Support\Interfaces\Services\PanelAttachmentHandlerServiceInterface;
use Adobrovolsky97\LaravelRepositoryServicePattern\Services\BaseCrudService;

class PanelAttachmentService extends BaseCrudService implements PanelAttachmentServiceInterface
{
    public function __construct(
        protected PanelAttachmentHandlerServiceInterface $panelAttachmentHandlerService,
        protected SerialPanelServiceInterface $serialPanelService,
    ) {
        parent::__construct();
    }

    public function assignHandler(PanelAttachment $panelAttachment, array $data){
        $this->panelAttachmentHandlerService->updateOrCreate([
            'panel_attachment_id' => $panelAttachment->id,
            'handles' => $data['handles'],
        ], 
        ['user_id' => auth()->user()->id,
        'handler_name' => auth()->user()->name,]);

        return $panelAttachment;
    }
    
    public function assignCustomAttachmentMaterial(PanelAttachment $panelAttachment, array $data): CustomAttachmentMaterial
    {
        return $panelAttachment->custom_attachment_materials()->updateOrCreate([
            'raw_material_id' => $data['raw_material_id'],
        ], [
            'qty' => $data['qty'],
        ]);
    }

    public function delete($keyOrModel): bool
    {
        $keyOrModel->panel_attachment_handlers()->each(function ($panelAttachmentHandler) {
            $this->panelAttachmentHandlerService->delete($panelAttachmentHandler);
        });

        $keyOrModel->serial_panels()->each(function ($serialPanel) {
            $this->serialPanelService->delete($serialPanel);
        });

        return parent::delete($keyOrModel); // TODO: Change the autogenerated stub
    }

    protected function getRepositoryClass(): string
    {
        return PanelAttachmentRepositoryInterface::class;
    }

    public function confirmKPM(PanelAttachment $panelAttachment, $request)
    {   
        $panelAttachment->status = $request['status'];
        
        $panelAttachment->save();

        return $panelAttachment;
    }

    public function update($panelAttachment, array $data): ?Model
    {   
        if (array_key_exists('note', $data)) {
            $panelAttachment->attachment_notes()->create(
                [
                    "note" => $data['note'],
                    "status" => $data['status'],
                ]
            );
            unset($data['note']);
        }
        
        return parent::update($panelAttachment, $data);
    }

    public function rejectKPM($panelAttachment, $request)
    {
        $note = $request->note;

        $panelAttachment = PanelAttachment::find($panelAttachment);

        $panelAttachment->status = PanelAttachmentStatusEnum::PENDING->value;

        $panelAttachment->attachment_notes()->create(
            [
                "note" => $note ? $note : "",
                "status" => PanelAttachmentStatusEnum::PENDING->value,
            ]
        );


        $panelAttachment->save();

        return $panelAttachment;
    }

    public function assignSpvAndReceiver(PanelAttachment $panelAttachment, array $data)
    {
        $panelAttachment->supervisor_id = $data['supervisor_id'] ?? auth()->user()->id;
        $attachmentHandler = [
            'handles' => PanelAttachmentHandlerHandlesEnum::RECEIVE->value,
        ];
        if (array_key_exists('receiver_name', $data)) {
            $attachmentHandler['handler_name'] = $data['receiver_name'];
        } else {
            $attachmentHandler['user_id'] = $data['receiver_id'];
        }
        $panelAttachment->panel_attachment_handlers()->create($attachmentHandler);
        $panelAttachment->save();
        return $panelAttachment;
    }
}