export const ROUTES = {
    DASHBOARD: 'dashboard',
    SERIAL_PANELS: 'serial-panels',
    WORK_DAYS: 'work-days',
    WORK_DAY_TIMES: 'work-day-times',
    PANEL_MATERIALS: 'panel-materials',
    PANEL_ATTACHMENT_HANDLERS: 'panel-attachment-handlers',
    PANEL_ATTACHMENTS: 'panel-attachments',
    CARRIAGE_PANEL_COMPONENTS: 'carriage-panel-components',
    USERS: 'users',
    PROFILE: 'profile',
    LOGOUT: 'logout',
    PERMISSIONS: 'permissions',
    ROLES: 'roles',
    DIVISIONS: 'divisions',
    WORKSHOPS: 'workshops',
    WORKSTATIONS: 'workstations',
    TRAINSETS: 'trainsets',
    PROJECTS: 'projects',
    PROJECTS_CARRIAGES: 'projects.carriages',
    PROJECTS_CARRIAGES_COMPONENTS: 'projects.carriages.components',
    PROJECTS_CARRIAGES_PANELS: 'projects.carriages.panels',
    PROJECTS_COMPONENTS: 'projects.components',
    PROJECTS_PANELS: 'projects.panels',
    PROJECTS_TRAINSETS: 'projects.trainsets',
    PROJECTS_TRAINSETS_COMPONENTS: 'projects.trainsets.components',
    PROJECTS_TRAINSETS_PANELS: 'projects.trainsets.panels',
    PROJECTS_TRAINSETS_CARRIAGES: 'projects.trainsets.carriage-trainsets',
    PROJECTS_TRAINSETS_DOWNLOAD_ATTACHMENT: 'projects.trainsets.download-attachment',
    PROJECTS_TRAINSETS_CARRIAGE_TRAINSETS_CARRIAGE_PANELS:
        'projects.trainsets.carriage-trainsets.carriage-panels',
    PROJECTS_TRAINSETS_CARRIAGE_TRAINSETS_CARRIAGE_PANELS_CARRIAGE_PANEL_COMPONENTS:
        'projects.trainsets.carriage-trainsets.carriage-panels.carriage-panel-components',
    PROJECTS_TRAINSETS_CARRIAGE_TRAINSETS_CARRIAGE_PANELS_CARRIAGE_PANEL_COMPONENTS_COMPONENT_MATERIALS:
        'projects.trainsets.carriage-trainsets.carriage-panels.carriage-panel-components.component-materials',
    PROJECTS_TRAINSETS_CARRIAGE_TRAINSETS_CARRIAGE_PANELS_PANEL_MATERIALS:
        'projects.trainsets.carriage-trainsets.carriage-panels.panel-materials',
    CARRIAGES: 'carriages',
    CARRIAGE_PRESETS: 'carriage-presets',
    PRESET_TRAINSETS: 'preset-trainsets',
    PANELS: 'panels',
    CARRIAGE_PANELS: 'carriage-panels',
    PROGRESS: 'progress',
    CARRIAGE_TRAINSETS: 'carriage-trainsets',
    RAW_MATERIALS: 'raw-materials',
    COMPONENTS: 'components',
    STEPS: 'steps',
    DETAIL_WORKER_PANELS: 'detail-worker-panels',
    PROGRESS_STEPS: 'progress-steps',
    TRAINSET_ATTACHMENTS: 'trainset-attachments',
    DETAIL_WORKER_TRAINSETS: 'detail-worker-trainsets',
    TRAINSET_ATTACHMENT_HANDLERS: 'trainset-attachment-handlers',
    COMPONENT_MATERIALS: 'component-materials',
    WORK_ASPECTS: 'work-aspects',
    TRAINSET_ATTACHMENT_COMPONENTS: 'trainset-attachment-components',
    FAILED_COMPONENT_MANUFACTURES: 'failed-component-manufactures',
    ATTACHMENT_NOTES: 'attachment-notes',
    FEEDBACK: 'feedback',
    CUSTOM_ATTACHMENT_MATERIALS: 'custom-attachment-materials',
    HELPDESK_CONTACT: 'helpdesk-contact',
    RETURNED_PRODUCTS: 'returned-products',
    PRODUCT_PROBLEMS: 'product-problems',
    REQUESTED_RETURNS: 'requested-returns',
    RETURNED_PRODUCT_NOTES: 'returned-product-notes',
    PRODUCT_PROBLEM_NOTES: 'product-problem-notes',
    REPLACEMENT_STOCKS: 'replacement-stocks',
	PRODUCT_RESTOCKS: 'product-restocks',
};
