export const ROUTES = {
    USERS: 'users',
    PROFILE: 'profile',
    LOGOUT: 'logout',
    PERMISSIONS: 'permissions',
    ROLES: 'roles',
    DIVISIONS: 'divisions',
    WORKSHOPS: 'workshops',
    WORKSTATIONS: 'workstations',
    TRAINSETS: 'trainsets',
    PROJECTS: 'projects',
    PROJECTS_TRAINSETS: 'projects.trainsets',
    PROJECTS_TRAINSETS_CARRIAGES: 'projects.trainsets.carriage-trainsets',
    PROJECTS_TRAINSETS_CARRIAGE_TRAINSETS_PANELS: 'projects.trainsets.carriage-trainsets.panels',
    CARRIAGES: 'carriages',
    CARRIAGE_PRESETS: 'carriage-presets',
    PRESET_TRAINSETS: 'preset-trainsets',
    PANELS: 'panels',
    CARRIAGE_PANELS: 'carriage-panels',
    PROGRESS: 'progress',
    CARRIAGE_TRAINSETS: 'carriage-trainsets',
    RAW_MATERIALS: 'raw-materials',
    COMPONENTS: 'components',
};
