name: Develop

on:
    push:
        branches:
            - dev

jobs:
    build-js-dev:
        name: Build JavaScript/CSS for Dev
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: NPM Build
              run: |
                  npm install
                  npm run build

    deploy-dev:
        name: Deploy dev
        runs-on: ubuntu-latest
        needs: [build-js-dev]
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: '8.1'
                  extensions: mbstring, bcmath
            - name: Composer install
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
